site_name: iberDok
  
nav:
  - Inicio: index.md
  - GuiaRapidaEditor: GuiaRapidaEditor.md
  - GuiaRapidaGestor: GuiaRapidaGestor.md
  - ManualBuenasPracticas: ManualBuenasPracticas.md
  - ManualdeAccesibilidaddelTeclado: ManualdeAccesibilidaddelTeclado.md
  - Version Selected: "../"

theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - i18n:
      default_language: en
      default_language_only: false
      docs_structure: folder
      languages:
        en:
          name: English
          build: true
        es:
          name: Spanish
          build: true
        ca:
          name: Catalan
          build: true
        eu:
          name: Euskera
          build: true
      nav_translations:
        es:
          Inicio: Inicio
          GuiaRapidaEditor: GuiaRapidaEditor
          GuiaRapidaGestor: GuiaRapidaGestor
          ManualBuenasPracticas: ManualBuenasPracticas
          ManualdeAccesibilidaddelTeclado: ManualdeAccesibilidaddelTeclado
        en:
          Inicio: Start
          GuiaRapidaEditor: QuickGuideEditor
          GuiaRapidaGestor: QuickGuideManager
          ManualBuenasPracticas: ManualGood Practices
          ManualdeAccesibilidaddelTeclado: Keyboard Accessibility Manual
        ca:
          Inicio: Inici
          GuiaRapidaEditor: GuiaRapidaEditor
          GuiaRapidaGestor: GuiaRapidaGestor
          ManualBuenasPracticas: ManualBonesPràctiques
          ManualdeAccesibilidaddelTeclado: Manuald'AccessibilitatdelTeclat
        eu:
          Inicio: Hasiera
          GuiaRapidaEditor: Editatzeko Gida Azkarra
          GuiaRapidaGestor: Gestiorako Gida Azkarra
          ManualBuenasPracticas: Praktika Onen Gida
          ManualdeAccesibilidaddelTeclado: Teklatuaren Erabilgarritasunaren Gida
  - mkdocs-video
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - mkdocs-versioning:
      version: 0.0.2
  - with-pdf:
      author: Equipo Migración
  - awesome-pages